-- Create Enum for User Roles
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('admin', 'editor');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create Profiles Table (Linked to Auth)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  role user_role DEFAULT 'editor',
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Site Configuration Table
CREATE TABLE IF NOT EXISTS site_config (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  logo_url TEXT DEFAULT '/logo.png',
  footer_text TEXT,
  seo_title TEXT DEFAULT 'SM Saúde e Seguros | Proteção para você e sua família',
  seo_description TEXT DEFAULT 'Consultoria especializada em planos de saúde e seguros. Proteja o que mais importa com a SM Saúde e Seguros.',
  og_image_url TEXT,
  contact_email TEXT DEFAULT 'contato@smsaudeseguros.com.br',
  contact_phone TEXT DEFAULT '(15) 99999-9999',
  contact_address TEXT DEFAULT 'Sorocaba, SP (Atendimento Nacional)',
  contact_whatsapp TEXT DEFAULT '5515999999999',
  social_instagram TEXT DEFAULT 'https://instagram.com',
  social_facebook TEXT DEFAULT 'https://facebook.com',
  social_linkedin TEXT DEFAULT 'https://linkedin.com',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Hero Section Table
CREATE TABLE IF NOT EXISTS hero_section (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  title TEXT NOT NULL,
  subtitle TEXT,
  cta_primary_text TEXT DEFAULT 'Fazer Cotação Personalizada',
  cta_primary_link TEXT DEFAULT '#contact',
  cta_secondary_text TEXT DEFAULT 'Conhecer a SM Saúde',
  cta_secondary_link TEXT DEFAULT '#about',
  hero_image_url TEXT,
  quote_text TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- About Section Table
CREATE TABLE IF NOT EXISTS about_section (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  title TEXT NOT NULL,
  description_1 TEXT,
  description_2 TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- About Spotlights (Benefits)
CREATE TABLE IF NOT EXISTS about_spotlights (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- About Images (Carousel)
CREATE TABLE IF NOT EXISTS about_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  alt_text TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Solutions (Services) Table
CREATE TABLE IF NOT EXISTS solutions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  icon_name TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  action_type TEXT DEFAULT 'form',
  action_link TEXT,
  button_text_card TEXT DEFAULT 'Cotar agora',
  button_text_form TEXT DEFAULT 'Quero receber minha cotação personalizada',
  pj_checkbox_text TEXT DEFAULT 'Tenho CNPJ',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Testimonials Table
CREATE TABLE IF NOT EXISTS testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  content TEXT NOT NULL,
  avatar_url TEXT,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- FAQ Table
CREATE TABLE IF NOT EXISTS faqs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  answer TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE hero_section ENABLE ROW LEVEL SECURITY;
ALTER TABLE about_section ENABLE ROW LEVEL SECURITY;
ALTER TABLE about_spotlights ENABLE ROW LEVEL SECURITY;
ALTER TABLE about_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE solutions ENABLE ROW LEVEL SECURITY;
ALTER TABLE testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE faqs ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Profiles
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
-- Note: 'admin' check relies on the user already being an admin, bootstrapping problem solved by manual insert or service role
CREATE POLICY "Admins can update all profiles" ON profiles FOR UPDATE USING (
  exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- Site Config & Sections: Read Public, Write Authenticated (Assuming any auth user is staff for now, since signup is closed)
-- Actually, strict RBAC would be better, but "auth.role() = 'authenticated'" is good for now as per requirement
-- "não é permitido adicionar novos usuarios, apenas administradores" -> so only staff exists.
CREATE POLICY "Read access for all" ON site_config FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON site_config FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Read access for all" ON hero_section FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON hero_section FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Read access for all" ON about_section FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON about_section FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Read access for all" ON about_spotlights FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON about_spotlights FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Read access for all" ON about_images FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON about_images FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Read access for all" ON solutions FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON solutions FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Read access for all" ON testimonials FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON testimonials FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Read access for all" ON faqs FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON faqs FOR ALL USING (auth.role() = 'authenticated');
-- Leads Table
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  interest TEXT,
  message TEXT,
  metadata JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Leads
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Leads Policies
-- Public can insert
CREATE POLICY "Public can insert leads" ON leads FOR INSERT WITH CHECK (true);
-- Admins can view
CREATE POLICY "Admins can view leads" ON leads FOR SELECT USING (auth.role() = 'authenticated');


-- Menu Items Table
CREATE TABLE IF NOT EXISTS menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  url TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Menu Items
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;

-- Menu Items Policies
CREATE POLICY "Read access for all" ON menu_items FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON menu_items FOR ALL USING (auth.role() = 'authenticated');

-- Add Header CTA fields to site_config
ALTER TABLE site_config ADD COLUMN IF NOT EXISTS header_cta_text TEXT DEFAULT 'Cotar Agora';
ALTER TABLE site_config ADD COLUMN IF NOT EXISTS header_cta_link TEXT DEFAULT '#contact';

-- Insert default menu items
INSERT INTO menu_items (label, url, sort_order) VALUES
('Início', '#hero', 10),
('Sobre', '#about', 20),
('Serviços', '#services', 30),
('Depoimentos', '#testimonials', 40),
('FAQ', '#faq', 50);
