# Supabase Setup

To use the contact form's lead capture feature, you need to set up a table in Supabase.

## Database Schema

Run the following SQL query in the Supabase SQL Editor to create the `leads` table and enable Row Level Security (RLS).

```sql
-- Create the leads table
CREATE TABLE leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  interest TEXT NOT NULL,
  message TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anyone (anon) to insert leads
-- This is necessary for a public contact form
CREATE POLICY "Enable insert for everyone" ON leads
  FOR INSERT
  WITH CHECK (true);

-- Create a policy to allow only authenticated users (admins) to view leads
-- You will need to create users in Supabase Auth to use this
CREATE POLICY "Enable read for authenticated users only" ON leads
  FOR SELECT
  USING (auth.role() = 'authenticated');
```

## Environment Variables

Ensure you have your Supabase URL and Anon Key in your `.env.local` file (or Vercel Environment Variables):

```bash
NEXT_PUBLIC_SUPABASE_URL=your-project-url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
```
