-- Create lead_interactions table
CREATE TABLE IF NOT EXISTS lead_interactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id BIGINT REFERENCES leads(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  interaction_type TEXT NOT NULL CHECK (interaction_type IN ('email', 'phone', 'whatsapp', 'personally')),
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE lead_interactions ENABLE ROW LEVEL SECURITY;

-- Create policies
DO $$ BEGIN
  CREATE POLICY "Authenticated users can view interactions" ON lead_interactions
    FOR SELECT USING (auth.role() = 'authenticated');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE POLICY "Authenticated users can insert interactions" ON lead_interactions
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;
