-- Create the webhook_logs table
CREATE TABLE IF NOT EXISTS webhook_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url TEXT NOT NULL,
  request_body JSONB,
  response_status INTEGER,
  response_headers JSONB,
  response_body TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE webhook_logs ENABLE ROW LEVEL SECURITY;

-- Admins can view and insert
CREATE POLICY "Admins can view webhook logs" ON webhook_logs FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Service can insert webhook logs" ON webhook_logs FOR INSERT WITH CHECK (true); -- Public/Service Role for inserts

-- Function to keep only the latest 100 rows
CREATE OR REPLACE FUNCTION truncate_webhook_logs()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM webhook_logs
  WHERE id NOT IN (
    SELECT id FROM webhook_logs
    ORDER BY created_at DESC
    LIMIT 100
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to execute the truncate function after insert
CREATE TRIGGER trigger_truncate_webhook_logs
AFTER INSERT ON webhook_logs
FOR EACH ROW
EXECUTE FUNCTION truncate_webhook_logs();
