-- Leads Table
CREATE TABLE IF NOT EXISTS leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  interest TEXT,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Leads
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

-- Leads Policies
-- Public can insert
CREATE POLICY "Public can insert leads" ON leads FOR INSERT WITH CHECK (true);
-- Admins can view
CREATE POLICY "Admins can view leads" ON leads FOR SELECT USING (auth.role() = 'authenticated');


-- Menu Items Table
CREATE TABLE IF NOT EXISTS menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  url TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Menu Items
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;

-- Menu Items Policies
CREATE POLICY "Read access for all" ON menu_items FOR SELECT USING (true);
CREATE POLICY "Write access for authenticated users" ON menu_items FOR ALL USING (auth.role() = 'authenticated');

-- Add Header CTA fields to site_config
ALTER TABLE site_config ADD COLUMN IF NOT EXISTS header_cta_text TEXT DEFAULT 'Cotar Agora';
ALTER TABLE site_config ADD COLUMN IF NOT EXISTS header_cta_link TEXT DEFAULT '#contact';

-- Insert default menu items
INSERT INTO menu_items (label, url, sort_order) VALUES
('Início', '#hero', 10),
('Sobre', '#about', 20),
('Serviços', '#services', 30),
('Depoimentos', '#testimonials', 40),
('FAQ', '#faq', 50);
